data<-read.table("UserData.csv",TRUE,",")
#head(data)
par(mfrow=c(2,2))
plot(data$age,data$income,xlab="Age",ylab="Income")
hist(data$age,xlab="Age",ylab="Number of people")
boxplot(data$income,ylab="Income")
summary(data$income)
boxplot(data$age,ylab="Age")
summary(data$age)